logging:
  level:
    root: info
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/yjg
    username: postgres
    password: 8DFn32P@$*,e!6

file:
  savePath: D:\practise\yjg\temp\files