logging:
  level:
    root: info
    com.holland.holland.mapper: debug
    com.holland.holland.mapper.LogMapper.insertSelective: info
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://119.23.68.6:5432/yjg
    username: postgres
    password: postgres

file:
  savePath: D:\practise\yjg\temp\files