eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/yjg
    username: postgres
    password: 8DFn32P@$*,e!6
  redis:
    host: localhost
    port: 6379
    password: 8DFn36P@$*,e!6
    token-timeout: 300
    token-key-prefix: "fp:"
